title = "Kira's Journey "
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = "ananke"
resourceDir = "resources"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
custom_css = ["css/my-styles.css"]

  text_color = ""
  author = ""
  favicon = ""
  site_logo = "logo3.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/keerthanna-kuyalavanathan-5b41621b1/"

[[params.ananke_socials]]
name = "GitHub"
url = "https://github.com/KiraK03"